=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjerciciosBasicosSchemas/public_html/pizzas.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="https://es.wikipedia.org/wiki/Pizza">
    <xs:element name="pizzas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pizza" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingrediente" maxOccurs="unbounded" minOccurs="3">
                                <xs:complexType>
                                    <xs:attribute name="nombre" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tipoDePizza" type="xs:string"></xs:attribute>
                        <xs:attribute name="precio" type="xs:integer"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjerciciosBasicosSchemas/public_html/Pizzas.xml
<?xml version="1.0" encoding="UTF-8"?>
<pizzas    xmlns="https://es.wikipedia.org/wiki/Pizza"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://es.wikipedia.org/wiki/Pizza pizzas.xsd">
    
    <pizza tipoDePizza="Barbacoa" precio="8">
        <ingrediente nombre="Salsa Barbacoa"/>
        <ingrediente nombre="Mozzarella"/>
        <ingrediente nombre="Pollo"/>
        <ingrediente nombre="Bacon"/>
        <ingrediente nombre="Ternera"/>
    </pizza>
    <pizza tipoDePizza="Margarita" precio="6">
        <ingrediente nombre="Tomate"/>
        <ingrediente nombre="JamÃ³n"/>
        <ingrediente nombre="Queso"/>
    </pizza>
</pizzas>
