=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjerciciosBasicosSchemas/public_html/selva.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="https://es.wikipedia.org/wiki/Selva">
    <xs:element name="selva">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="animal" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="tipo" type="xs:string"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="edad" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="genero"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjerciciosBasicosSchemas/public_html/Selva.xml
<?xml version="1.0" encoding="UTF-8"?>
<selva      xmlns="https://es.wikipedia.org/wiki/Selva"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://es.wikipedia.org/wiki/Selva selva.xsd">
    <animal genero="Macho">
        <nombre>Werthers</nombre>
        <tipo>Pantera</tipo>
        <color>Negro</color>
        <edad>12</edad>
     </animal>
    <animal genero="Hembra">
        <nombre>Bun</nombre>
        <tipo>León</tipo>
        <color>Marrón</color>
        <edad>15</edad>
     </animal>
    <animal genero="Macho">
        <nombre>Ifirt</nombre>
        <tipo>Gato</tipo>
        <color>Nranja</color>
        <edad>12</edad>
     </animal>
</selva>
