=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/ExRecuLM/public_html/lotr.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings"
    targetNamespace="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings"
    elementFormDefault="qualified">
    
    <xs:complexType name="lotr">
        <xs:sequence>
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="nombre" type="xs:string"/>
                    <xs:element name="ubicacion" type="xs:string"/>
                    <xs:element name="habitantes">
                        <xs:complexType>
                          <xs:simpleContent>
                            <xs:extension base="xs:string">
                              <xs:attribute name="tipo" type="xs:string" use="optional"/>
                            </xs:extension>
                          </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="clima" type="xs:string"/>
                    <xs:element name="personajesIlustres">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                      </xs:sequence>
                    </xs:complexType>
                    </xs:element>
                    <xs:element name="esperanzaVida" type="xs:string" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute name="id" type="xs:string" use="required"/>
            </xs:complexType>
            <xs:complexType name="origenType">
                <xs:sequence>
                  <xs:element name="nacimiento" type="xs:string"/>
                  <xs:element name="familia" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="magiaType">
                <xs:sequence>
                  <xs:element name="poder" type="xs:string"/>
                  <xs:element name="evolucion" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="heroeType">
                <xs:sequence>
                  <xs:element name="nombreHeroe" type="xs:string"/>
                  <xs:element name="mision" type="xs:string"/>
                  <xs:choice>
                    <xs:element name="origen" type="origenType"/>
                    <xs:element name="magia" type="magiaType"/>
                  </xs:choice>
                  <xs:element name="objetoMagico" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="lotr">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="regiones">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="lugar" type="lugarType" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="compania">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="heroe" type="heroeType" minOccurs="1" maxOccurs="6"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="xmlns" type="xs:anyURI" use="required"/>
                  <xs:attribute name="xmlns:xsi" type="xs:anyURI" use="required"/>
                  <xs:attribute name="xsi:schemaLocation" type="xs:anyURI" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
  </xs:schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/ExRecuLM/public_html/lotr.xml
<?xml version="1.0"?>
<lotr xmlns="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://en.wikipedia.org/wiki/The_Lord_of_the_Rings lotr.xsd">

    <regiones>
        <lugar id="r01">
            <nombre>La Comarca</nombre>
            <ubicacion>Noroeste de la Tierra Media</ubicacion>	
            <habitantes tipo="medianos">Hobbits</habitantes>
            <clima>Oceanico</clima>
            <personajesIlustres>
                    <nombre>Bilbo</nombre>
                    <nombre>Sam</nombre>
                    <nombre>Merry</nombre>
                    <nombre>Frodo</nombre>
            </personajesIlustres>
        </lugar>
        <lugar id="r02">
            <nombre>Rivendel</nombre>
            <ubicacion>Centro de la Tierra Media</ubicacion>	
            <habitantes tipo="medianos">Elfos</habitantes>
            <clima>Templado</clima>
            <personajesIlustres>
                    <nombre>Legolas</nombre>
                    <nombre>Galadriel</nombre>
                    <nombre>Celebron</nombre>
            </personajesIlustres>
            <esperanzaVida>Eterna</esperanzaVida>
        </lugar>
        <lugar id="r03">
            <nombre>Mordor</nombre>
            <ubicacion>Este de la Tierra Media</ubicacion>	
            <habitantes>Orcos</habitantes>
            <clima>Ventoso</clima>
            <personajesIlustres>
                    <nombre>Sauron</nombre>
                    <nombre>Ella la ara√±a</nombre>
                    <nombre>Gollum</nombre>
            </personajesIlustres>
        </lugar>
    </regiones>
    <compania>
        <heroe>
            <nombreHeroe>Frodo</nombreHeroe>
            <mision>Portador del anillo</mision>
            <origen>
                    <nacimiento codigo="r01">La comarca</nacimiento>
                    <familia>Bolson</familia>
            </origen>
            <objetoMagico>Anillo unico</objetoMagico>
        </heroe>
        <heroe>
            <nombreHeroe>Legolas</nombreHeroe>
            <mision>Proteger a Frodo</mision>
            <origen>
                    <nacimiento codigo="r02">Rivendel</nacimiento>
                    <familia>Elfica</familia>
            </origen>
            <objetoMagico>Arco</objetoMagico>
        </heroe>
        <heroe>
            <nombreHeroe>Gandalf el gris</nombreHeroe>
            <mision>Proteger a Frodo</mision>
            <magia>
                    <poder>Magia gris</poder>
                    <evolucion>Gandalf el Blanco</evolucion>
            </magia>
            <objetoMagico>Baston</objetoMagico>
        </heroe>
    </compania>
</lotr>
