=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/DTD/public_html/Ejercicio3.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contrato (clausula+,epilogo?)>
<!ELEMENT clausula (epigrafe+)>
<!ELEMENT epigrafe (#PCDATA)>
<!ELEMENT epilogo (#PCDATA)>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/DTD/public_html/Ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contrato SYSTEM "Ejercicio3.dtd">
<contrato>
    <clausula>
        <epigrafe>dgjoksghborhno</epigrafe>
        <epigrafe>arfh</epigrafe>
        <epigrafe>fadshaetjqwat</epigrafe>
        <epigrafe>fsadgeah5taehfagfgf</epigrafe>
    </clausula>
    <clausula>
        <epigrafe>fsadgeah5taehfagfgf</epigrafe>
        <epigrafe>fsadgeah5taehfagfgf</epigrafe>
    </clausula>
    <clausula>
        <epigrafe>fsadgeah5taehfagfgf</epigrafe>
        <epigrafe>fsadgeah5taehfagfgf</epigrafe>
        <epigrafe>fsadgeah5taehfagfgf</epigrafe>
    </clausula>
    <epilogo></epilogo>
</contrato>
