=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/DTD/public_html/Ejercicio1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT correo (mail+)>
<!ELEMENT mail (para,cc?,cco?,asunto,cuerpo)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/DTD/public_html/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE correo SYSTEM "Ejercicio1.dtd">
<correo>
    <mail>
        <para>Pablo Motos</para>
        <cc></cc>
        <cco></cco>
        <asunto>F1</asunto>
        <cuerpo>Invita al Nano al Hormiguero</cuerpo>
    </mail>
    <mail>
        <para>Luis</para>
        <cc></cc>
        <cco></cco>
        <asunto>IMPORTANTE</asunto>
        <cuerpo>Me cago en tu puta madre</cuerpo>
    </mail>
</correo>
