=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/DTD/public_html/Ejercicio5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT plantilla (trabajador)*>
<!ELEMENT trabajador (nombre,sueldo,posicion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT sueldo (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>

<!ATTLIST trabajador
          idEmpleado ID #REQUIRED
          idJefe IDREF #IMPLIED>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/DTD/public_html/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plantilla SYSTEM "Ejercicio5.dtd">
<plantilla>
    <trabajador idEmpleado="e01">
        <nombre></nombre>
        <sueldo></sueldo>
        <posicion></posicion>
    </trabajador>
    <trabajador idEmpleado="e02" idJefe="e01">
        <nombre></nombre>
        <sueldo></sueldo>
        <posicion></posicion>
    </trabajador>
    <trabajador idEmpleado="e03" idJefe="e01">
        <nombre></nombre>
        <sueldo></sueldo>
        <posicion></posicion>
    </trabajador>
</plantilla>
