=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/DTD/Ejercicio3DTD.dtd
<!ELEMENT contrato (clausulas,epilogo)>
<!ELEMENT clausulas (clausula+)>
<!ELEMENT clausula (epigrafes,desarrollo+)>
<!ELEMENT epigrafes (#PCDATA)>
<!ELEMENT desarrollo (#PCDATA)>
<!ELEMENT epilogo (#PCDATA)>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/Ejercicio3DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE contrato SYSTEM "DTD/Ejercicio3DTD.dtd">
<contrato>
	<clausulas>
		<clausula>
			<epigrafes>1ºEpigrafe</epigrafes>
			<desarrollo>BLABLMEDAGEGOPEG</desarrollo>
		</clausula>
		<clausula>
			<epigrafes>1ºEpigrafe</epigrafes>
			<desarrollo>BLABLMEDAGEGOPEG</desarrollo>
		</clausula>
	</clausulas>
	<epilogo>Epilogo contrato</epilogo>
</contrato>
