=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/DTD/EJERCICIOIDIDREF.dtd
<!ELEMENT plantilla (trabajador)*>
<!ELEMENT trabajador (nombre, sueldo, posición)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT sueldo (#PCDATA)>
<!ELEMENT posición (#PCDATA)>
<!ATTLIST trabajador idEmpleado ID #REQUIRED
						idJefe IDREF #REQUIRED>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/EJERCICIOIDIDREF.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE plantilla SYSTEM "EJERCICIOIDIDREF.dtd">
<plantilla>
	<trabajador idEmpleado="p1">
		<nombre></nombre>
		<sueldo></sueldo>
		<posición></posición>
	</trabajador>
	<trabajador idEmpleado="p2" idJefe="p1">
		<nombre></nombre>
		<sueldo></sueldo>
		<posición></posición>
	</trabajador>
	<trabajador idEmpleado="p3" idJefe="p1">
		<nombre></nombre>
		<sueldo></sueldo>
		<posición></posición>
	</trabajador>
	<trabajador idEmpleado="p4" idJefe="p1">
		<nombre></nombre>
		<sueldo></sueldo>
		<posición></posición>
	</trabajador>
</plantilla>
