=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/DTD/telefono.dtd
<!ELEMENT teléfonos (teléfono)*>
	<!ELEMENT teléfono (numeroSerial, datos_terminal, cámaras)>
		<!ELEMENT numeroSerial (#PCDATA)>
		<!ELEMENT datos_terminal (marca, modelo, pantalla, sistemaOperativo, carcasa)>
			<!ELEMENT marca (#PCDATA)>
			<!ELEMENT modelo (#PCDATA)>
			<!ELEMENT pantalla (tamaño, tecnología, densidadDePuntos)>
				<!ELEMENT tamaño (#PCDATA)>
				<!ELEMENT tecnología (#PCDATA)>
				<!ELEMENT densidadDePuntos (#PCDATA)>
			<!ELEMENT sistemaOperativo (#PCDATA)>
			<!ELEMENT carcasa (color)>
				<!ELEMENT color (#PCDATA)>
		<!ELEMENT cámaras (cámara)*>
			<!ELEMENT cámara (resolución)>
				<!ELEMENT resolución (#PCDATA)>

<!ATTLIST

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/telefono.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE teléfonos SYSTEM "telefono.dtd">
<teléfonos>
	<teléfono id="T001">
		<numeroSerial>16541984</numeroSerial>
		<datos_terminal>
			<marca></marca>
			<modelo></modelo>
			<pantalla>
				<tamaño></tamaño>
				<tecnología></tecnología>
				<densidadDePuntos></densidadDePuntos>
			</pantalla>
			<sistemaOperativo SO="Windows"></sistemaOperativo>
			<carcasa material="">
				<color></color>
			</carcasa>
		</datos_terminal>
		<cámaras>
			<cámara tipo="frontal">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
		</cámaras>
	</teléfono>
	<teléfono id="T002">
		<numeroSerial>59479812</numeroSerial>
		<datos_terminal>
			<marca></marca>
			<modelo></modelo>
			<pantalla>
				<tamaño></tamaño>
				<tecnología></tecnología>
				<densidadDePuntos></densidadDePuntos>
			</pantalla>
			<sistemaOperativo SO="Android"></sistemaOperativo>
			<carcasa material="">
				<color></color>
			</carcasa>
		</datos_terminal>
		<cámaras>
			<cámara tipo="frontal">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
		</cámaras>
	</teléfono>
	<teléfono id="T003">
		<numeroSerial>35748989</numeroSerial>
		<datos_terminal>
			<marca></marca>
			<modelo></modelo>
			<pantalla>
				<tamaño></tamaño>
				<tecnología></tecnología>
				<densidadDePuntos></densidadDePuntos>
			</pantalla>
			<sistemaOperativo SO="iOS"></sistemaOperativo>
			<carcasa material="">
				<color></color>
			</carcasa>
		</datos_terminal>
		<cámaras>
			<cámara tipo="frontal">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
			<cámara tipo="trasera">
				<resolución></resolución>
			</cámara>
		</cámaras>
	</teléfono>
</teléfonos>
