=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/PruebaDTD/public_html/editor.dtd
<!ELEMENT editor (parrafo)+>
<!ELEMENT parrafo (#PCDATA | cursiva | negrita)*>
<!ELEMENT cursiva (#PCDATA | negrita)*>
<!ELEMENT negrita (#PCDATA | cursiva)*>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/PruebaDTD/public_html/editor.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE editor SYSTEM "editor.dtd">
<editor>
    <parrafo>Hola me llamo Pepe</parrafo>
    <parrafo>Hola me llamo <negrita>Pepe</negrita></parrafo>
    <parrafo>Hola me llamo <negrita>Pepe, soy de <cursiva>Villaverde Bajo</cursiva></negrita></parrafo>
    <parrafo>¿Cómo estas? <negrita>Estoy <cursiva>bien</cursiva></negrita></parrafo>
</editor>
