=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjemplosEsquemas/public_html/libro.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://es.wikipedia.org/wiki/El_Senor_de_los_Anillos"
           elementFormDefault="qualified">
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="indice">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="capitulo1" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="capitulo2">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="capitulo3">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="capituloFinal">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="intro" type="xs:string"/>
                                        <xs:element name="nudo" type="xs:string"/>
                                        <xs:element name="desarrollo" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="protagonista">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="mote" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="apellido" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/XML/Ejercicio3XSD.xml
<?xml version="1.0"?>
<libro	xmlns="https://es.wikipedia.org/wiki/El_Señor_de_los_Anillos"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://es.wikipedia.org/wiki/El_Señor_de_los_Anillos libro.xsd">
	<titulo>El señor de los anillos</titulo>
	<indice>
		<capitulol nombre="La comunidad de anillo"> 
			Se reune la comunidad del anillo en Rivendel y llegan a la conclusion de que lo mejor es destruir el anillo unico.
		</capitulol>
		<capitulo2 nombre="Las dos torres">
			Se separa la comunidad por problemas con Boromir, acaban luchando contra las ordas de Saruman en el abismo de Helm, mientras Frodo se adentra en Mordor.
		</capitulo2>
		<capitulo3 nombre="El retorno del rey">
			Gondor une fuerzas con Theoden para luchar contra el ejercito de Sauron y Frodo es capaz de destruir el anillo con ayuda de Gollum.
		</capitulo3>
		<capituloFinal nombre="The final chapter">
			<intro>
				Divertida a la par que interesante.
			</intro>
			<nudo>
				No puedes dejar de leer pero sobran algunas descipciones.
			</nudo>
			<desarrollo>
				Todo acaba bien, la Tierra Media es salvada!
			</desarrollo>
		</capituloFinal>
	</indice>
	<protagonista>
		<nombre mote="El portador del anillo">Frodo</nombre>
		<apellido>Bolson</apellido>
	</protagonista>
</libro>
