=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/Ejercicio4XSD/public_html/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            targetNamespace="https://es.wikipedia.org/wiki/persona">
    
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="apellidos" type="xs:string"></xs:element>
                            <xs:element name="dni" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="puestoTrabajo" type="xs:string"></xs:element>
                                <xs:element name="lugarEstudios" type="xs:string"></xs:element>
                            </xs:choice>
                            <xs:element name="descripcion">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="coloOjos" type="xs:string"></xs:element>
                                        <xs:element name="altura" type="xs:string"></xs:element>
                                        <xs:element name="peso" type="xs:integer"></xs:element>
                                        <xs:element name="colorCabello" type="xs:string"></xs:element>
                                        <xs:element name="personalidad">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="tipoDePersonalidad" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="edad" type="xs:integer"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="idPersona" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/Ejercicio4XSD/public_html/Ejercicio4XSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas   xmlns="https://es.wikipedia.org/wiki/persona" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="https://es.wikipedia.org/wiki/persona persona.xsd">

    <persona idPersona="001">
        <nombre>Juan</nombre>
        <apellidos>Perez Rubiales</apellidos>
        <dni>467839487P</dni>
        <puestoTrabajo>Informatico</puestoTrabajo>
        <descripcion>
                <coloOjos>Verdes</coloOjos>
                <altura>1,80</altura>
                <peso>75</peso>
                <colorCabello>Moreno</colorCabello>
                <personalidad tipoDePersonalidad="Majete">
                        Soy una persona simpatica y agradable
                </personalidad>
        </descripcion>
        <edad>35</edad>
    </persona>
    <persona idPersona="002">
        <nombre>Maria</nombre>
        <apellidos>Aranda Gonzalez</apellidos>
        <dni>4674809487P</dni>
        <lugarEstudios>IES Virgen de la Paz</lugarEstudios>
        <descripcion>
                <altura>1,80</altura>
                <peso>75</peso>
                <personalidad tipoDePersonalidad="Agradable">
                        Soy una persona buena y soñadora.
                </personalidad>
                <coloOjos>Verdes</coloOjos>
                <colorCabello>Moreno</colorCabello>
        </descripcion>
        <edad>25</edad>
    </persona>
    <persona idPersona="003">
        <nombre>Juanan</nombre>
        <apellidos>Romero Jimenez</apellidos>
        <dni>9674809487P</dni>
        <puestoTrabajo>Policia</puestoTrabajo>
        <descripcion>
                <coloOjos>Negros</coloOjos>
                <altura>1,88</altura>
                <peso>80</peso>
                <personalidad tipoDePersonalidad="Autoritario">
                        Me gusta el orden y la ley
                </personalidad>
                <colorCabello>Castaño</colorCabello>
        </descripcion>
        <edad>25</edad>
    </persona>
</personas>
