=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EXAMEN3ErTRIMESTRE/EjemplosEsquemas/public_html/cine.xsd
<?xml version="1.0"?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="cine">
        <complexType>
            <sequence>
                <element name="pelicula" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="titulo">
                                <complexType>
                                    <simpleContent>
                                        <extension base="string">
                                            <attribute name="idioma" type="string" use="optional"/>
                                        </extension>
                                    </simpleContent>
                                </complexType>
                            </element>
                            <element name="director" type="string"/>
                            <element name="estreno" type="string"/>
                            <element name="reparto">
                                <complexType>
                                    <sequence>
                                        <element name="actor" type="string" minOccurs="1" maxOccurs="unbounded"/>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="categoria" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>    
</schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjemplosEsquemas/public_html/cine.xml
<?xml version="1.0" encoding="UTF-8"?>
<cine   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="cine.xsd">
    <pelicula categoria="accion">
        <titulo>Mad Max</titulo>
        <director>George Miller</director>
        <estreno>15 mayo 2015</estreno>
        <reparto>
            <actor>Tom Hardy</actor>
            <actor>Charlize Theron</actor>
            <actor>Nicholas Hoult</actor>
        </reparto>
    </pelicula>
    <pelicula categoria="animacion">
        <titulo idioma="ingles">Inside Out</titulo>
        <director>Pete Docter</director>
        <estreno>17 junio 2015</estreno>
        <reparto>
            <actor>Amy Poehler</actor>
            <actor>Phyllis Smith</actor>
            <actor>Bill Hader</actor>
        </reparto>
    </pelicula>
</cine>
