=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EXAMEN3ErTRIMESTRE/EjemplosEsquemas/public_html/poemas.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="poemas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="poema" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="verso" type="xs:string" minOccurs="3" maxOccurs="3"/>
                        </xs:sequence>
                        <xs:attribute name="fecha" type="xs:string" use="required"/>
                        <xs:attribute name="lugar" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BigBan0511/EjerciciosHTML-CSS-JAVASCRIPT/EjemplosEsquemas/public_html/poemas.xml
<?xml version="1.0" encoding="UTF-8"?>
<poemas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="poemas.xsd">
    <poema fecha="Abril de 1915" lugar="Granada">
        <titulo>Alba</titulo>
        <verso>Mi corazón oprimido</verso>
        <verso>late junto a la alborada</verso>
        <verso>el dolor de sus amores...</verso>
    </poema>
    <poema fecha="1903" lugar="Sevilla">
        <titulo>Arde en tus ojos un misterio, virgen</titulo>
        <verso>esquiva y compañera.</verso>
        <verso>No sé si es odio o es amor la lumbre</verso>
        <verso>inagotable de tu aliaba negra.</verso>
    </poema>
</poemas>
